### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MareoRaft** [ghseeli/grad-school-notes#64]
Can we put a license on this to protect free sharing of information?  Perhaps the MIT license or GNU copyleft?

**Comment by ghseeli** [comment]
We have to be careful with licensing. My largest concern is that not all of the content of the materials is exclusively original. Some questions are copied from Tan and/or Stewart. That being said, a lot of Calculus problems are probably part of some public domain. Perhaps we can talk to someone with more expertise.

**Comment by MareoRaft** [comment]
I meant for the grad-school-notes repository.

**Comment by ghseeli** [comment]
Oh oops. So, my concern there is with the specific notes that are more of, uh, transcriptions.

**Comment by ghseeli** [comment]
I guess we can always license specific works. Also, we might run into issues with software licenses. Are we licensing the written math or the TeX code? https://choosealicense.com/non-software/

**Comment by ghseeli** [comment]
I guess, having no license is actually more restrictive, in that with no license, we the contributors reserve exclusive access to the use of our TeX code, except for GitHub terms of service exceptions. Perhaps, then, we should stick an MIT license. Copyleft is a dangerous game, I think, but perhaps it is worth playing in this case. Let’s discuss more tomorrow.
